import { it, expect } from 'vitest';
import { emitOutputs } from './emitOutputs';
import { sweepWorlds } from './worldSweep';

// The artifacts are regenerated by the suite, so a committed RUN_OUTPUT.txt can
// never drift from the code that produced it without a test run noticing.
it('emits both artifacts and they say what they measured', () => {
  const { run, sweep } = emitOutputs('2026-09-05T00:00:00.000Z');
  expect(run).toContain('PLANT RECOVERY');
  expect(run).toContain('isAdmissible() === false');
  expect(sweep).toContain('0 refused to build.');
  expect(sweep).toContain('RATE ok');
  // NOT `expect(sweep).not.toContain('SOMETIMES')` — that was my own
  // badly-denominated assertion: the word appears in the render's own
  // explanation of what a SOMETIMES means, so the check tested for a STRING
  // and claimed to test a CONDITION. Assert on the structured report instead.
  expect(sweepWorlds('2026-09-05T00:00:00.000Z').unstable).toEqual([]);
});
