CREATE EXTENSION IF NOT EXISTS postgis;
CREATE SCHEMA IF NOT EXISTS payload_corpus;
REVOKE ALL ON SCHEMA payload_corpus FROM PUBLIC;

CREATE TABLE IF NOT EXISTS payload_corpus.schema_migrations (
  version integer PRIMARY KEY,
  name text NOT NULL UNIQUE,
  sha256 text NOT NULL CHECK (sha256 ~ '^[a-f0-9]{64}$'),
  applied_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE OR REPLACE FUNCTION payload_corpus.current_tenant()
RETURNS text LANGUAGE sql STABLE PARALLEL SAFE AS $$
  SELECT NULLIF(current_setting('payload.tenant_id', true), '')
$$;

CREATE OR REPLACE FUNCTION payload_corpus.can_read_scope(candidate text)
RETURNS boolean LANGUAGE sql STABLE PARALLEL SAFE AS $$
  SELECT candidate = 'global'
    OR candidate = 'customer:' || COALESCE(payload_corpus.current_tenant(), '')
$$;

CREATE OR REPLACE FUNCTION payload_corpus.can_write_scope(candidate text)
RETURNS boolean LANGUAGE sql STABLE PARALLEL SAFE AS $$
  SELECT (candidate = 'global' AND current_setting('payload.allow_global_write', true) = 'on')
    OR candidate = 'customer:' || COALESCE(payload_corpus.current_tenant(), '')
$$;

CREATE TABLE IF NOT EXISTS payload_corpus.corpus_records (
  sequence bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope text NOT NULL CHECK (scope = 'global' OR scope ~ '^customer:[a-z0-9][a-z0-9._-]{1,63}$'),
  tenant_id text GENERATED ALWAYS AS (
    CASE WHEN scope LIKE 'customer:%' THEN substring(scope FROM 10) ELSE NULL END
  ) STORED,
  record_id text NOT NULL UNIQUE CHECK (record_id ~ '^[A-Za-z0-9][A-Za-z0-9:._/-]{2,255}$'),
  record_type text NOT NULL CHECK (record_type IN ('evidence','evidence_unit','entity','alias','relationship','observation','assertion')),
  known_at text NOT NULL,
  known_at_time timestamptz NOT NULL,
  known_to text,
  known_to_time timestamptz,
  recorded_at text NOT NULL,
  recorded_at_time timestamptz NOT NULL,
  previous_hash text CHECK (previous_hash IS NULL OR previous_hash ~ '^[a-f0-9]{64}$'),
  record_hash text NOT NULL UNIQUE CHECK (record_hash ~ '^[a-f0-9]{64}$'),
  record_json jsonb NOT NULL,
  geom geometry(Point, 4326),
  CHECK (known_at_time = known_at::timestamptz),
  CHECK ((known_to IS NULL AND known_to_time IS NULL) OR (known_to_time = known_to::timestamptz AND known_to_time > known_at_time)),
  CHECK (recorded_at_time = recorded_at::timestamptz),
  CHECK (record_json ->> 'recordId' = record_id),
  CHECK (record_json ->> 'recordType' = record_type),
  CHECK (record_json ->> 'knownAt' = known_at),
  UNIQUE(sequence, scope, record_id, record_type, known_at, recorded_at, record_hash)
);

CREATE OR REPLACE FUNCTION payload_corpus.sync_record_geometry()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.record_type = 'entity'
     AND jsonb_typeof(NEW.record_json #> '{location,lat}') = 'number'
     AND jsonb_typeof(NEW.record_json #> '{location,lng}') = 'number' THEN
    NEW.geom := ST_SetSRID(ST_MakePoint(
      (NEW.record_json #>> '{location,lng}')::double precision,
      (NEW.record_json #>> '{location,lat}')::double precision
    ), 4326);
  ELSE
    NEW.geom := NULL;
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS corpus_records_sync_geometry ON payload_corpus.corpus_records;
CREATE TRIGGER corpus_records_sync_geometry
BEFORE INSERT OR UPDATE OF record_json ON payload_corpus.corpus_records
FOR EACH ROW EXECUTE FUNCTION payload_corpus.sync_record_geometry();

CREATE INDEX IF NOT EXISTS corpus_records_scope_sequence
  ON payload_corpus.corpus_records(scope, sequence);
CREATE INDEX IF NOT EXISTS corpus_records_scope_type_known
  ON payload_corpus.corpus_records(scope, record_type, known_at_time, sequence);
CREATE INDEX IF NOT EXISTS corpus_records_tenant_sequence
  ON payload_corpus.corpus_records(tenant_id, sequence) WHERE tenant_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS corpus_records_geom_gist
  ON payload_corpus.corpus_records USING gist(geom) WHERE geom IS NOT NULL;

CREATE TABLE IF NOT EXISTS payload_corpus.corpus_outbox_events (
  sequence bigint PRIMARY KEY,
  event_id text NOT NULL UNIQUE,
  scope text NOT NULL,
  tenant_id text GENERATED ALWAYS AS (
    CASE WHEN scope LIKE 'customer:%' THEN substring(scope FROM 10) ELSE NULL END
  ) STORED,
  record_id text NOT NULL UNIQUE,
  record_type text NOT NULL,
  known_at text NOT NULL,
  known_at_time timestamptz NOT NULL,
  occurred_at text NOT NULL,
  occurred_at_time timestamptz NOT NULL,
  record_hash text NOT NULL UNIQUE,
  CHECK (known_at_time = known_at::timestamptz),
  CHECK (occurred_at_time = occurred_at::timestamptz),
  CHECK (event_id = 'corpus-event:' || record_hash),
  FOREIGN KEY(sequence, scope, record_id, record_type, known_at, occurred_at, record_hash)
    REFERENCES payload_corpus.corpus_records(sequence, scope, record_id, record_type, known_at, recorded_at, record_hash)
    ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS corpus_outbox_scope_sequence
  ON payload_corpus.corpus_outbox_events(scope, sequence);
CREATE INDEX IF NOT EXISTS corpus_outbox_tenant_sequence
  ON payload_corpus.corpus_outbox_events(tenant_id, sequence) WHERE tenant_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS payload_corpus.corpus_projector_checkpoints (
  projector text NOT NULL,
  scope text NOT NULL CHECK (scope = 'global' OR scope ~ '^customer:[a-z0-9][a-z0-9._-]{1,63}$'),
  tenant_id text GENERATED ALWAYS AS (
    CASE WHEN scope LIKE 'customer:%' THEN substring(scope FROM 10) ELSE NULL END
  ) STORED,
  sequence bigint NOT NULL CHECK (sequence >= 0),
  updated_at text NOT NULL,
  updated_at_time timestamptz NOT NULL,
  PRIMARY KEY(projector, scope),
  CHECK (updated_at_time = updated_at::timestamptz)
);

CREATE OR REPLACE FUNCTION payload_corpus.guard_projector_checkpoint()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  maximum_sequence bigint;
BEGIN
  IF TG_OP = 'UPDATE' AND NEW.sequence < OLD.sequence THEN
    RAISE EXCEPTION 'CORPUS_PROJECTION_CHECKPOINT_REGRESSION: checkpoints may only advance' USING ERRCODE = '23514';
  END IF;
  SELECT COALESCE(MAX(sequence), 0) INTO maximum_sequence
  FROM payload_corpus.corpus_outbox_events
  WHERE scope = 'global' OR scope = NEW.scope;
  IF NEW.sequence > maximum_sequence THEN
    RAISE EXCEPTION 'CORPUS_PROJECTION_CHECKPOINT_INVALID: sequence is beyond the visible outbox' USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS corpus_projector_checkpoint_guard ON payload_corpus.corpus_projector_checkpoints;
CREATE TRIGGER corpus_projector_checkpoint_guard
BEFORE INSERT OR UPDATE ON payload_corpus.corpus_projector_checkpoints
FOR EACH ROW EXECUTE FUNCTION payload_corpus.guard_projector_checkpoint();

ALTER TABLE payload_corpus.corpus_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE payload_corpus.corpus_outbox_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE payload_corpus.corpus_projector_checkpoints ENABLE ROW LEVEL SECURITY;
ALTER TABLE payload_corpus.corpus_records FORCE ROW LEVEL SECURITY;
ALTER TABLE payload_corpus.corpus_outbox_events FORCE ROW LEVEL SECURITY;
ALTER TABLE payload_corpus.corpus_projector_checkpoints FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS corpus_records_read ON payload_corpus.corpus_records;
CREATE POLICY corpus_records_read ON payload_corpus.corpus_records
  FOR SELECT TO payload_corpus_query, payload_corpus_ingest, payload_corpus_projector, payload_corpus_compiler
  USING (payload_corpus.can_read_scope(scope));
DROP POLICY IF EXISTS corpus_records_owner ON payload_corpus.corpus_records;
CREATE POLICY corpus_records_owner ON payload_corpus.corpus_records
  FOR ALL TO payload_corpus_owner USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS corpus_records_ingest ON payload_corpus.corpus_records;
CREATE POLICY corpus_records_ingest ON payload_corpus.corpus_records
  FOR INSERT TO payload_corpus_ingest
  WITH CHECK (payload_corpus.can_write_scope(scope));

DROP POLICY IF EXISTS corpus_outbox_read ON payload_corpus.corpus_outbox_events;
CREATE POLICY corpus_outbox_read ON payload_corpus.corpus_outbox_events
  FOR SELECT TO payload_corpus_query, payload_corpus_ingest, payload_corpus_projector, payload_corpus_compiler
  USING (payload_corpus.can_read_scope(scope));
DROP POLICY IF EXISTS corpus_outbox_owner ON payload_corpus.corpus_outbox_events;
CREATE POLICY corpus_outbox_owner ON payload_corpus.corpus_outbox_events
  FOR ALL TO payload_corpus_owner USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS corpus_outbox_ingest ON payload_corpus.corpus_outbox_events;
CREATE POLICY corpus_outbox_ingest ON payload_corpus.corpus_outbox_events
  FOR INSERT TO payload_corpus_ingest
  WITH CHECK (payload_corpus.can_write_scope(scope));

DROP POLICY IF EXISTS corpus_checkpoints_read ON payload_corpus.corpus_projector_checkpoints;
CREATE POLICY corpus_checkpoints_read ON payload_corpus.corpus_projector_checkpoints
  FOR SELECT TO payload_corpus_query, payload_corpus_ingest, payload_corpus_projector, payload_corpus_compiler
  USING (payload_corpus.can_read_scope(scope));
DROP POLICY IF EXISTS corpus_checkpoints_owner ON payload_corpus.corpus_projector_checkpoints;
CREATE POLICY corpus_checkpoints_owner ON payload_corpus.corpus_projector_checkpoints
  FOR ALL TO payload_corpus_owner USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS corpus_checkpoints_write ON payload_corpus.corpus_projector_checkpoints;
CREATE POLICY corpus_checkpoints_write ON payload_corpus.corpus_projector_checkpoints
  FOR ALL TO payload_corpus_projector, payload_corpus_compiler
  USING (payload_corpus.can_write_scope(scope))
  WITH CHECK (payload_corpus.can_write_scope(scope));

GRANT USAGE ON SCHEMA payload_corpus TO payload_corpus_ingest, payload_corpus_query, payload_corpus_projector, payload_corpus_compiler;
GRANT ALL PRIVILEGES ON SCHEMA payload_corpus TO payload_corpus_owner;
REVOKE ALL ON FUNCTION payload_corpus.current_tenant() FROM PUBLIC;
REVOKE ALL ON FUNCTION payload_corpus.can_read_scope(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION payload_corpus.can_write_scope(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION payload_corpus.sync_record_geometry() FROM PUBLIC;
REVOKE ALL ON FUNCTION payload_corpus.guard_projector_checkpoint() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION payload_corpus.current_tenant(), payload_corpus.can_read_scope(text)
  TO payload_corpus_ingest, payload_corpus_query, payload_corpus_projector, payload_corpus_compiler, payload_corpus_owner;
GRANT EXECUTE ON FUNCTION payload_corpus.can_write_scope(text)
  TO payload_corpus_ingest, payload_corpus_projector, payload_corpus_compiler, payload_corpus_owner;
GRANT EXECUTE ON FUNCTION payload_corpus.sync_record_geometry()
  TO payload_corpus_ingest, payload_corpus_owner;
GRANT EXECUTE ON FUNCTION payload_corpus.guard_projector_checkpoint()
  TO payload_corpus_projector, payload_corpus_compiler, payload_corpus_owner;
GRANT SELECT ON payload_corpus.schema_migrations TO payload_corpus_ingest, payload_corpus_query, payload_corpus_projector, payload_corpus_compiler;
GRANT SELECT ON payload_corpus.corpus_records TO payload_corpus_ingest, payload_corpus_query, payload_corpus_projector, payload_corpus_compiler;
GRANT INSERT ON payload_corpus.corpus_records TO payload_corpus_ingest;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA payload_corpus TO payload_corpus_ingest;
GRANT SELECT ON payload_corpus.corpus_outbox_events TO payload_corpus_ingest, payload_corpus_query, payload_corpus_projector, payload_corpus_compiler;
GRANT INSERT ON payload_corpus.corpus_outbox_events TO payload_corpus_ingest;
GRANT SELECT ON payload_corpus.corpus_projector_checkpoints TO payload_corpus_ingest, payload_corpus_query;
GRANT SELECT, INSERT, UPDATE ON payload_corpus.corpus_projector_checkpoints TO payload_corpus_projector, payload_corpus_compiler;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA payload_corpus TO payload_corpus_owner;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA payload_corpus TO payload_corpus_owner;
