CREATE OR REPLACE FUNCTION payload_corpus.reject_agent_artifact_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'CORPUS_AGENT_ARTIFACT_IMMUTABLE: rows cannot be updated or deleted' USING ERRCODE = '55000';
END $$;

CREATE TABLE IF NOT EXISTS payload_corpus.agent_artifacts (
  sequence bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope text NOT NULL CHECK (scope = 'global' OR scope ~ '^customer:[a-z0-9][a-z0-9._-]{1,63}$'),
  tenant_id text GENERATED ALWAYS AS (
    CASE WHEN scope LIKE 'customer:%' THEN substring(scope FROM 10) ELSE NULL END
  ) STORED,
  artifact_id text NOT NULL UNIQUE CHECK (artifact_id ~ '^[A-Za-z0-9][A-Za-z0-9:._/-]{2,255}$'),
  artifact_type text NOT NULL CHECK (artifact_type IN ('agent_result', 'build_attestation')),
  corpus_build_id text NOT NULL CHECK (corpus_build_id ~ '^[A-Za-z0-9][A-Za-z0-9:._/-]{2,255}$'),
  recorded_at text NOT NULL,
  recorded_at_time timestamptz NOT NULL,
  previous_hash text CHECK (previous_hash IS NULL OR previous_hash ~ '^[a-f0-9]{64}$'),
  artifact_hash text NOT NULL UNIQUE CHECK (artifact_hash ~ '^[a-f0-9]{64}$'),
  artifact_json jsonb NOT NULL,
  CHECK (recorded_at_time = recorded_at::timestamptz),
  CHECK (artifact_json ->> 'artifactId' = artifact_id),
  CHECK (artifact_json ->> 'artifactType' = artifact_type),
  CHECK (artifact_json ->> 'corpusBuildId' = corpus_build_id),
  UNIQUE(sequence, scope, artifact_id, artifact_type, corpus_build_id, recorded_at, artifact_hash)
);

CREATE INDEX IF NOT EXISTS agent_artifacts_scope_sequence
  ON payload_corpus.agent_artifacts(scope, sequence);
CREATE INDEX IF NOT EXISTS agent_artifacts_tenant_sequence
  ON payload_corpus.agent_artifacts(tenant_id, sequence) WHERE tenant_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS agent_artifacts_build_type_sequence
  ON payload_corpus.agent_artifacts(corpus_build_id, artifact_type, sequence DESC);

DROP TRIGGER IF EXISTS agent_artifacts_no_update ON payload_corpus.agent_artifacts;
CREATE TRIGGER agent_artifacts_no_update
BEFORE UPDATE ON payload_corpus.agent_artifacts
FOR EACH ROW EXECUTE FUNCTION payload_corpus.reject_agent_artifact_mutation();
DROP TRIGGER IF EXISTS agent_artifacts_no_delete ON payload_corpus.agent_artifacts;
CREATE TRIGGER agent_artifacts_no_delete
BEFORE DELETE ON payload_corpus.agent_artifacts
FOR EACH ROW EXECUTE FUNCTION payload_corpus.reject_agent_artifact_mutation();

ALTER TABLE payload_corpus.agent_artifacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE payload_corpus.agent_artifacts FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS agent_artifacts_read ON payload_corpus.agent_artifacts;
CREATE POLICY agent_artifacts_read ON payload_corpus.agent_artifacts
  FOR SELECT TO payload_corpus_query, payload_corpus_ingest, payload_corpus_projector, payload_corpus_compiler
  USING (payload_corpus.can_read_scope(scope));
DROP POLICY IF EXISTS agent_artifacts_owner ON payload_corpus.agent_artifacts;
CREATE POLICY agent_artifacts_owner ON payload_corpus.agent_artifacts
  FOR ALL TO payload_corpus_owner USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS agent_results_append ON payload_corpus.agent_artifacts;
CREATE POLICY agent_results_append ON payload_corpus.agent_artifacts
  FOR INSERT TO payload_corpus_query
  WITH CHECK (artifact_type = 'agent_result' AND payload_corpus.can_read_scope(scope));
DROP POLICY IF EXISTS build_attestations_append ON payload_corpus.agent_artifacts;
CREATE POLICY build_attestations_append ON payload_corpus.agent_artifacts
  FOR INSERT TO payload_corpus_compiler
  WITH CHECK (artifact_type = 'build_attestation' AND payload_corpus.can_write_scope(scope));

REVOKE ALL ON FUNCTION payload_corpus.reject_agent_artifact_mutation() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION payload_corpus.reject_agent_artifact_mutation()
  TO payload_corpus_query, payload_corpus_compiler, payload_corpus_owner;
GRANT SELECT ON payload_corpus.agent_artifacts
  TO payload_corpus_ingest, payload_corpus_query, payload_corpus_projector, payload_corpus_compiler;
GRANT INSERT ON payload_corpus.agent_artifacts TO payload_corpus_query, payload_corpus_compiler;
GRANT USAGE, SELECT ON SEQUENCE payload_corpus.agent_artifacts_sequence_seq TO payload_corpus_query, payload_corpus_compiler;
GRANT ALL PRIVILEGES ON payload_corpus.agent_artifacts TO payload_corpus_owner;
